config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :albums
  root to: "home#index"

  resources :albums do 
    member do
      delete :delete_image_attachment
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_one_attached :cover_picture
    has_many_attached :images
    has_many :taggings
    has_many :tags, through: :taggings, :dependent => :delete_all 
    
    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
      end
      
      def all_tags
        self.tags.map(&:name).join(", ")
      end

    validates :album_name, presence: true
    validates :created_by, presence: true
    validates :description, presence: true, length: {minimum: 10}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true


  def all_tags=(names)
    self.tags = names.split(",").map do |name|
        Tag.where(name: name.strip).first_or_create!
    end
  end
  
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :albums, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :albums

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, 
         :confirmable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
        
        def index
          # @albums= Album.all
          @q = Album.ransack(params[:q])
          @albums = @q.result.includes(:tags, :taggings)
        end
      
        def show
          @album = Album.find(params[:id])
        end
      
        def new
          @album = current_user.albums.new
        end
      
        def create
          @album = current_user.albums.new(album_params)
        
          if @album.save
            redirect_to 'albums/index'
          else
            render :new
          end
        end
      
      def edit
        @album = Album.find(params[:id])
      end
      
      def update
        @album = Album.find(params[:id])
      
        if @album.update(album_params)
          redirect_to @album
        else
          render :edit
        end
      end
      
      def destroy
        @album = Album.find(params[:id])
        @album.destroy
        redirect_to root_path
      end

      def delete_image_attachment
        @image = ActiveStorage::Blob.find_signed(params[:id])
        @image.attachments.first.purge
        redirect_to albums_url
      end
      
      private
      def album_params
        params.require(:album).permit(:album_name, :cover_picture, :delete_image_attachment, :created_by, :description, :published, :all_tags,images: [] )
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @albums = Album.where(published: true)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/albums/_form.html.erb
<%= form_with model: @album do |form| %>
  <div>
    <%= form.label :album_name %><br>
    <%= form.text_field :album_name %>
    <% @album.errors.full_messages_for(:album_name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :created_by %><br>
    <%= form.text_area :created_by %><br>
  </div>

    <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% @album.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
   </div>

   <div class="form-group">
     <%= form.label :cover_picture %>
       <%=form.file_field :cover_picture %>
    </div>

    <div class="form-group">
     <%= form.label :images %>
       <%=form.file_field :images , multiple: true%>
    </div>

    <div class="form-group">
    <%= form.label :add_tags   %>
      <%= form.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>

    <div>
     <%=form.check_box :published %>
     <%= form.label :published %>
    </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/_internal.html.erb
<% albums.each do |album| %>
<div class="container-fluid mb-3 pt-5 bott">
    <div class=" row g-0">
        <div class="col-md-6 ">
            <% if album.cover_picture.attached? %>
              <%= image_tag(album.cover_picture, :alt => "...", :class=>'img-fluid w-100') %>
              <% else %>
              <%= "pehle lgane toh de tbhi hi dikhegi na bhaiyaji" %>
              <% end %>
        </div>
        <div class="col-md-6">
          <div class="card-body">
            <h3 class="card-title"><%= link_to album.album_name, album, :class =>'text-uppercase text-decoration-none btn btn-info' %></h3>
            <p class="card-text">By:  <%= album.created_by %></p>
            <p class="">About the album:   </p>
            <p class="card-text ml-5"><%= album.description %></p>
          </div>
        </div>
    </div>
</div>
<%end%>

app/views/albums/edit.html.erb
<div class="container w-50">
<h1 class="pt-3 pb-2">Edit album</h1>

<%= render "form", album: @album %>

</div>

app/views/albums/index.html.erb
<%= search_form_for @q do |f| %> 
    <%= f.search_field :tags_name_cont , :placeholder=>"Search"%>
     <%= f.submit "Search", :class =>'btn btn-primary' %>
<% end %>
<div class="container ">
<h1 class="pt-3 pb-5 text-center text-uppercase" 
    style="font-size:70px; background-color: lightgrey; color:green">My Albums</h1>
<div class="row ">
<% current_user.albums.each do |album| %>
    <div class="cardd card col-4 pt-3 pb-2">
        <div class="" style="width: 18rem;"> 
          <% if album.cover_picture.attached? %>
          <%= image_tag(album.cover_picture, :class => "photu", :width => 300 , :height =>200) %>
          <% else %>
          <%= "pehle lga toh lo tbhi hi dikhegi" %>
          <% end %>
            <div class="card-body">
              <h5 class="card-title text-center"><%= link_to album.album_name, album, :class =>'text-decoration-none howr ' %></h5>
               <p class="card-text mt-2" style="text-decoration: underline "><strong>Created By:-  </strong></p>
               <p class="card-text text-center border-bottom pb-2 "><%= album.created_by %></p>
               <strong class="card-text" style="text-decoration: underline ">Tags generated:- </strong>
               <p class="card-text text-center border-bottom pb-2" style="background-color:  "><%= album.all_tags%></p>
            </div>
        </div>
    </div>
<% end %>
</div>
</div>

app/views/albums/new.html.erb
<div class="container w-50">
<h1>New Album</h1>
 
<%= render "form" %>
</div>

app/views/albums/show.html.erb
<div class="container w-50 text-left">

<h1 class="text-center text-uppercase" style="background-color: grey; color: #00ffff; " ><%= @album.album_name %></h1>
<div style="background-color: #ffff99">
<h4 class="pt-3 " style="text-decoration: underline "><strong>Created by:    </strong></h4>
<h2 class="text-uppercase text-center pb-2" style="color: blue"><%= @album.created_by %></h2>
</div>
  <h5 class="pt-2 text-decoration-underline " style="text-decoration: underline "><strong>Cover picture of the album:-    </strong></h5>
  <% if @album.cover_picture.attached? %>
        <%= image_tag(@album.cover_picture, :width => 600 , :height =>400) %>
        <div class="text-center ">
              <% if user_signed_in? %>
                <%= link_to 'Remove Cover Image', delete_image_attachment_album_url(@album.cover_picture.signed_id), class: "btn btn-danger my-3 w-50",
                                                method: :delete,
                                                data: { confirm: 'Are you sure?' } %>
              <% end %>
        </div>
  <% else %>
          <p class="text-center">Pehle lga toh lo tbhi hi dikhegi</p>
  <% end %>

<h4 class="pt-3 " style="text-decoration: underline "><strong>Attached Images:    </strong></h4>
<% if @album.images.attached? %>
                <% @album.images.each do |image| %>
                        <%= image_tag(image, :class => "illustrations bott") %>
                        <div class="text-center">
                        <% if user_signed_in? %>
                              <%= link_to 'Remove Photo', delete_image_attachment_album_url(image.signed_id), class: "btn btn-danger my-3",
                                         method: :delete,
                                         data: { confirm: 'Are you sure?' } %>
                        <% end %>
                        </div>
                <% end %>
<% else %>
    <p class="text-center">Not Yet</p>
<% end %>

<h4 class="pt-4" style="text-decoration: underline "><strong>Description of the album:    </strong></h4>
<p class=" text-center pt-3 pb-2" style="background-color: #ffff99"><%= @album.description %></p>

<ul style="list-style-type:none; " class="listt pt-5 d-flex justify-content-around">
  <% if user_signed_in? %>
  <li>
  <h5><%= link_to "Edit", edit_album_path(@album), :class=>'btn btn-outline-warning btn-lg' %></h5>
  </li>
  <li>
  <h5 ><%= link_to "Destroy", album_path(@album), 
                  :class =>'text-decoration-none btn btn-outline-danger btn-lg',
                  method: :delete,
                  data: { confirm: "Are you sure?" }%></h5>
</li>
<li>
<h5><%= link_to 'Back', root_path, :class=>'btn btn-outline-dark btn-lg'  %></h5>
</li>
<% else %>
<li>
<h5><%= link_to 'Back', root_path, :class=>'btn btn-outline-dark btn-lg'  %></h5>
</li>
<% end %>
</ul>
</div>

app/views/home/_internal.html.erb
<div class="container pt-5">
<div class=" mb-3" style="max-width: 840px;">
  <div class="row g-0">
    <div class="col-md-4">
        <% if album.cover_picture.attached? %>
          <%= image_tag(album.cover_picture, :alt => "...", :width => 300 , :height =>200) %>
          <% else %>
          <%= "pehle lga toh lo tbhi hi dikhegi" %>
          <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= link_to album.album_name, album, :class =>'text-decoration-none howr' %></h5>
        <p class="card-text"><small class="text-muted"><%= @album.created_by %></small></p>
        <p class="card-text"><%= @album.description %></p>
        
      </div>
    </div>
  </div>
</div>

app/views/home/_navi.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Gallery', root_path , class: 'navbar-brand btn btn-info' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">              
        <% if user_signed_in? %>
        <li class="nav-item">
                <%= link_to "New Album", new_album_path, class: 'nav-link butt' %>
                </li>
            <li class="nav-item">
                <%= link_to 'Sign out', destroy_user_session_path , method: :delete, class: 'nav-link butt3' %>
                </li>
                
        <% else %>
            <li class="nav-item">
            <%= link_to 'Register',  new_user_registration_path, class: 'nav-link butt' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign in',  new_user_session_path, class: 'nav-link butt' %>
             </li>   
        <% end %>
        
            
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
  <script type="text/javascript">
    window.location.href="/albums"  // put your correct path in a string here
  </script>
<% else %>
<div class="container">
<h1 class="d-flex justify-content-center text-primary pt-3" >Welcome to gallery app</h1>
<h4 class="d-flex justify-content-center text-success">Some albums of our users</h4>
       
   <div class="container ">
                <%= render 'albums/internal',albums: @albums %>
                
   </div>
</div>    
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <!--Bootstrap file -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <%= render 'home/navi' %>
         <p class="notice"><%= notice %></p>
         <p class="alert"><%= alert %></p>      
          <%= yield %>
           
          
</html>